/* 
  人事任用單取消確認時產生對應單資料
  建立日期：2017/05/16
*/
 
 UPdate HR_CHGENR SET FMSTS ='{3}' WHERE FMNO ='{0}';
DELETE FROM HR_EMPLYM WHERE EMPLYID ='{1}';
Delete From HR_WRKSET where EMPLYID ='{1}';
DELETE FROM HR_PERD WHERE EMPLYID ='{1}';    
DELETE FROM HR_EMGCNT WHERE EMPLYID ='{1}';  
DELETE FROM HR_RPSNT WHERE EMPLYID ='{1}';   
DELETE FROM HR_WRKSET WHERE EMPLYID ='{1}';  
DELETE FROM HR_EMPYFRNEW WHERE EMPLYID ='{1}'; 
DELETE FROM HR_ACNTNO WHERE EMPLYID ='{1}' ; 
Delete From [192.168.100.19].CCM_Main.dbo.EMPNO where EMP_NO ='{1}'