
Update ##ITEM Set  
         WAHO_NO = 'KA1' ,  -- 儲區
         LOCA_NO = 'XX' ,   -- 儲位         
         VD_NO = NULL ,     -- 廠商編號
         INV_EMP_NO = '' ,  -- 倉庫人員          
         PUR_EMP_NO = '' ,  -- 採購人員
         MOC_EMP_NO = '' ,  -- 生管人員 
         MTR_CST = 0 ,      -- 材料成本             
         LAB_CST = 0 ,      -- 人工成本
         OVH_CST = 0 ,      -- 製費成本
         SBC_CST = 0 ,      -- 加工費用
         LAB_ADD = 0 ,      -- 本階人工
         OVH_ADD = 0 ,      -- 本階製費               
         SBC_ADD = 0 ,      -- 本階加工
         MTR_ADD = 0 ,      -- 本階材料
         STD_PCHPRC = 0 ,   -- 標準進價
         STD_SALPRC = 0 ,   -- 標準售價
         STD_SALEXP = 0 , 
		 MTR_RT = 1 ,       -- 聯產品材料權數  
		 LAB_RT = 1 ,       -- 聯產品人工權數    
		 OVH_RT = 1 ,       -- 聯產品製費權數   
		 SBC_RT = 1         -- 聯產品加工權數 	
		 -- 更新為預設值	